### ISSUE TITLE
HEAP_SIZE_RATIO should not be static by default

### ISSUE THREAD

**Issue by l15k4** [lustefaniak/docker-gcp-java#1]
I think that this image should compute `HEAP_SIZE_RATIO` based on memory available (cgroup) and `HEAP_SIZE_RATIO` env variable should be exported only to override it. We could have something like : 
```
<= 256 (50%)
<= 512 (60%)
<= 1024 (70%)
<= 2048 (80%)
<= 4096 (90%)
<= 8192 (92%)
<= 12288 (93%)
<= 16384 (94%)
<= 20480 (95%)
> 20480 (96%)  
```

Something like this would be ideal for any apps that don't use FS caching or off heap memory in any way.

**Comment by lustefaniak** [comment]
You mean the default value of '80%' in https://github.com/lustefaniak/docker-gcp-java/blob/master/setup-env.d/35-java-env.bash#L34 should be automatically determined by available memory?

**Comment by l15k4** [comment]
Rather "default heap size ratio" should be automatically determined by available memory ... the percentage should be determined by it ... In a nutshell, we would give as much HEAP as possible to the application while having enough memory for the OS and other off-heap things.

**Comment by lustefaniak** [comment]
@l15k4 I'm thinking about introducing MAX_NON_HEAP_SIZE_MB which would default to `total memory` by default, and check if calculated non_heap > max - in such case adjust RATIO, wdyt? That way it won't break existing behaviour and will work well for large memory limits
